version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.prod
    command: uwsgi --ini uwsgi.ini
    volumes:
      - ../static:/app/static
    environment:
      - ENV=prod
    depends_on:
      - db
    ports:
      - "8000:8000"

  db:
    image: postgres:15
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  nginx:
    image: nginx:1.21
    volumes:
      - ../static:/static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  pgdata: